//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novych.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NovychResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NovychResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novych.Resources.NovychResources", typeof(NovychResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parni.cistic.karcher@gmail.com.
        /// </summary>
        public static string AdminMail {
            get {
                return ResourceManager.GetString("AdminMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123987456.
        /// </summary>
        public static string AdminPhone {
            get {
                return ResourceManager.GetString("AdminPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novych.cz/ParniCistic.
        /// </summary>
        public static string AppAddress {
            get {
                return ResourceManager.GetString("AppAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.novych@gmail.com.
        /// </summary>
        public static string AppMail {
            get {
                return ResourceManager.GetString("AppMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xeqacydmpwbmamqv.
        /// </summary>
        public static string AppMailPassword {
            get {
                return ResourceManager.GetString("AppMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        public static string AppMailSmtp {
            get {
                return ResourceManager.GetString("AppMailSmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        public static string AppMailSmtpPort {
            get {
                return ResourceManager.GetString("AppMailSmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novych.cz.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervuj.
        /// </summary>
        public static string BtnCreateReservation {
            get {
                return ResourceManager.GetString("BtnCreateReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat Log.
        /// </summary>
        public static string BtnDeleteLog {
            get {
                return ResourceManager.GetString("BtnDeleteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit rezervaci.
        /// </summary>
        public static string BtnDeleteReservation {
            get {
                return ResourceManager.GetString("BtnDeleteReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat Návštěvníky.
        /// </summary>
        public static string BtnDeleteVisitors {
            get {
                return ResourceManager.GetString("BtnDeleteVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string DbAddress {
            get {
                return ResourceManager.GetString("DbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string DbClass {
            get {
                return ResourceManager.GetString("DbClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string DbDate {
            get {
                return ResourceManager.GetString("DbDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vytvoření.
        /// </summary>
        public static string DbDateCreated {
            get {
                return ResourceManager.GetString("DbDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum smazání.
        /// </summary>
        public static string DbDateDeleted {
            get {
                return ResourceManager.GetString("DbDateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadej datum.
        /// </summary>
        public static string DbDateValidation {
            get {
                return ResourceManager.GetString("DbDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string DbDesc {
            get {
                return ResourceManager.GetString("DbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string DbEmail {
            get {
                return ResourceManager.GetString("DbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadej e-mail.
        /// </summary>
        public static string DbEmailValidation {
            get {
                return ResourceManager.GetString("DbEmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikator.
        /// </summary>
        public static string DbIdentifier {
            get {
                return ResourceManager.GetString("DbIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Adresa.
        /// </summary>
        public static string DbIpAddress {
            get {
                return ResourceManager.GetString("DbIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpráva.
        /// </summary>
        public static string DbMessage {
            get {
                return ResourceManager.GetString("DbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string DbName {
            get {
                return ResourceManager.GetString("DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        public static string DbPhone {
            get {
                return ResourceManager.GetString("DbPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadej telefoní číslo.
        /// </summary>
        public static string DbPhoneValidation {
            get {
                return ResourceManager.GetString("DbPhoneValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušení rezervace.
        /// </summary>
        public static string DialogTitleDeleteReservation {
            get {
                return ResourceManager.GetString("DialogTitleDeleteReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová rezervace.
        /// </summary>
        public static string DialogTitleNewReservation {
            get {
                return ResourceManager.GetString("DialogTitleNewReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Vyber hodnotu ---.
        /// </summary>
        public static string FilterChoose {
            get {
                return ResourceManager.GetString("FilterChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je rovno.
        /// </summary>
        public static string FilterIsEqual {
            get {
                return ResourceManager.GetString("FilterIsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není rovno.
        /// </summary>
        public static string FilterIsNotEqual {
            get {
                return ResourceManager.GetString("FilterIsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pá.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čt.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Út.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
